// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package src

import (
	"database/sql"
)

type Snippet struct {
	ID             string
	SnippetsListID string
	Title          string
	Content        string
	CreatedAt      sql.NullTime
}

type SnippetsList struct {
	ID        string
	Name      string
	CreatedAt sql.NullTime
}

type Todo struct {
	ID        string
	Title     string
	CreatedAt sql.NullTime
}
